-- Tabla agencia: sucursales/puntos de atención por operadora
-- Ejecutar en Supabase → SQL Editor

CREATE TABLE IF NOT EXISTS public.agencia (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_operadora bigint NOT NULL REFERENCES public.operadora(id) ON DELETE CASCADE,
  lugar text NOT NULL,
  direccion text,
  contactos text,
  hora_atencion text,
  encomiendas_contacto text,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_agencia_id_operadora ON public.agencia(id_operadora);

ALTER TABLE public.agencia ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "agencia_select_authenticated" ON public.agencia;
DROP POLICY IF EXISTS "agencia_insert_authenticated" ON public.agencia;
DROP POLICY IF EXISTS "agencia_update_authenticated" ON public.agencia;
DROP POLICY IF EXISTS "agencia_delete_authenticated" ON public.agencia;

CREATE POLICY "agencia_select_authenticated" ON public.agencia
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "agencia_insert_authenticated" ON public.agencia
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "agencia_update_authenticated" ON public.agencia
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "agencia_delete_authenticated" ON public.agencia
  FOR DELETE TO authenticated USING (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.agencia TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE agencia_id_seq TO authenticated;
