-- Tabla publicidad (no existía en backup agosto 2025, pero la app la requiere)
CREATE TABLE IF NOT EXISTS public.publicidad (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descripcion text,
  referencia text,
  direccion text,
  mapa text,
  numerocelular text,
  video text,
  likes numeric DEFAULT 0
);

ALTER TABLE public.publicidad ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable read access for all users" ON public.publicidad;
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON public.publicidad;
DROP POLICY IF EXISTS "Enable update for users based on email" ON public.publicidad;
DROP POLICY IF EXISTS "Enable delete for users based on user_id" ON public.publicidad;

CREATE POLICY "Enable read access for all users" ON public.publicidad
  FOR SELECT USING (true);

CREATE POLICY "Enable insert for authenticated users only" ON public.publicidad
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Enable update for users based on email" ON public.publicidad
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Enable delete for users based on user_id" ON public.publicidad
  FOR DELETE TO authenticated USING (true);

GRANT SELECT ON public.publicidad TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.publicidad TO authenticated;

-- Reescribir URLs del proyecto Supabase antiguo al nuevo (misma ruta en Storage)
UPDATE public.multimedia
SET video = REPLACE(video, 'rgnpwminvztocawdbvus', 'drdluixfeolnwcwxhgeg')
WHERE video LIKE '%rgnpwminvztocawdbvus%';

-- Marcar como sin video los que sigan inválidos (archivo no migrado a Storage)
UPDATE public.multimedia
SET video = 'link'
WHERE video IS NOT NULL
  AND video <> 'link'
  AND video NOT LIKE '%drdluixfeolnwcwxhgeg.supabase.co%';

-- Nota: si un video da 400 en Storage, vuelve a subirlo desde Destinos en el panel admin
